export enum CategoryEnum {
  ARTS = 'arts',
  AUTOMOBILES = 'automobiles',
  BOOKS = 'books',
  BUSINESS = 'business',
  FASHION = 'fashion',
  FOOD = 'food',
  HEALTH = 'health',
  HOME = 'home',
  INSIDER = 'insider',
  MAGAZINE = 'magazine',
  MOVIES = 'movies',
  NY_REGION = 'nyregion',
  OBTUARIES = 'obituaries',
  OPNION = 'opinion',
  POLITICS = 'politics',
  REAL_STATE = 'realestate',
  SCIENCE = 'science',
  SPORTS = 'sports',
  SUNDAY_REVIEW = 'sundayreview',
  TECHNOLOGY = 'technology',
  THEATER = 'theater',
  T_MAGAZINE = 't-magazine',
  TRAVEL = 'travel',
  UPSHOT = 'upshot',
  US = 'us',
  WORLD = 'world',
}
